      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          start: npm run dev
          # quote the url to be safe against YML parsing surprises
          wait-on: 'http://localhost:3000'
          browser: 'Replay Firefox'
      - name: Upload
        uses: replayio/action-upload@v0.4.5
        with:
          api-key: rwk_yMZyfiLd4na4AypdZ6xPJIaSxOJnQzb2kuaYxgeYceX
          public: true
